print("y0u 4re H4ck")
scaredyou = input("Enter Password:")
print("ravioli")
print("Here on this snowy peak, I get my internet through a single strand of copper wire. I've grown lonely over the years.")
print("Enter response number:")
print("1: How long have you been up there?")
print("2: Why am I hack?")
print("3: Do you have a good ravioli recipe?")
question1 = input("Enter number for responce(1,2,or 3)")
if question1 == 1:
  print("Oh its been so long I can hardly remember. The icy winds freeze me to my core. The bitter taste of canned ravioli is my only comfort. I don't remember how I got this way. All I can remember now is the tart sauce, and those creamy pouches. They quench my undying hunger but do not satisfy me.")